version: "3.8"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test12345"
    ports:
      - "1433:1433"
    networks:
      - backend

  account:
    build:
      context: ./account-service
    ports:
    - "3004:3004"
    command: sh -c "/wait"
    environment:
      WAIT_HOSTS: sql-server-db:1433
      WAIT_BEFORE: 60
    networks:
      - backend
    depends_on:
      - sql-server-db
    restart: on-failure
  connection:
    build:
      context: ./connection-service
    ports:
      - "3005:3005"
  delivery:
    build:
      context: ./delivery-service
    ports:
      - "3002:3002"
  orders:
    build:
      context: ./GetAllOrders
    ports:
      - "3001:3001"
  restaurants:
    build:
      context: ./restaurant-service
    ports:
      - "3003:3003"

networks:
  backend:
    driver: bridge

#  nginx:
#    depends_on:
#      - account
#      - connection
#      - delivery
#      - orders
#      - restaurants
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx-1.20.1
#    ports:
#      - "3050:80"